# 02c – 4. Experiment: Modell-Vergleich: Whisper Large-v3 (Audio-Only) vs. AV-HuBERT

## Motivation

Nachdem Fine-Tuning-Ansätze (02a, 02b) keine Verbesserung gegenüber BL4 brachten,
wird hier ein grundlegend anderes Modell getestet: **Whisper Large-v3** als
reines Audio-ASR-System (kein visueller Input).

**Hypothese:** Whisper ist ein state-of-the-art generisches ASR-Modell. Kann es
trotz fehlendem visuellem Input mit BL4 mithalten?

## Ergebnis (Vorschau)

| Modell | WER | Joint Error |
|--------|-----|-------------|
| Whisper Large-v3 | ~1.03 | ~0.59 |
| BL4 (beam=12, len=20) | ~0.495 | ~0.324 |

Whisper ist **~52 % schlechter** in WER und ~45 % schlechter in Joint Error.
In der überlappenden Mehrsprecher-Umgebung von MCoRec ist visueller Input entscheidend.

**Hinweis zum Bugfix:** Dieser Lauf wurde **vor dem Bugfix** in `segmentation.py` durchgeführt (`min_duration_off` las fälschlicherweise den Wert von `min_duration_on`). Das ist **gewollt**: Der Bugfix wurde erst nach Abschluss der LLM- und Hyperparameter-Experimente entdeckt. Da der Bugfix allein die WER zunächst verschlechterte, wurde erst in `02j_`/`02k_` die Kombination aus Bugfix + `min_duration`-Optimierung erarbeitet, die schließlich das beste Ergebnis lieferte.

## 1 – Setup: Arbeitsverzeichnis & Imports

In [1]:
import os, sys
import pandas as pd

# Arbeitsverzeichnis auf Repo-Root setzen (Voraussetzung für alle relativen Pfade)
project_baseline_path = "/home/josch080/Projektgruppe/mcorec_baseline"
os.chdir(project_baseline_path)

# Repo-Root in sys.path, damit projektinterne Module importierbar sind
if project_baseline_path not in sys.path:
    sys.path.append(project_baseline_path)

from script.pg_utils_experiments import run_inference_for_experiment, run_eval_and_log, append_eval_results_for_experiments

## 2 – Modell-Definition

`whisper_audio` ist eine in `inference.py` ergänzte Modellklasse, die
Whisper rein audio-basiert betreibt – ohne Lip-Crop-Input.
Der Checkpoint-Name wird direkt an die openai-whisper-Bibliothek übergeben.

In [2]:
MODELS = {
    "whisper_large_v3": {
        "model_type": "whisper_audio",
        # Checkpoint-Name gemäß openai-whisper-Konvention:
        # Optionen: "tiny", "base", "small", "medium", "large-v2", "large-v3"
        "chkpt": "large-v3"}
}

## 3 – Sessions & Experimente

Gleiches 5-Session-Subset für direkte Vergleichbarkeit mit allen vorherigen Experimenten.

In [3]:
SESSION_IDS = ["session_40", "session_43", "session_49", "session_50", "session_54"]

In [4]:
EXPERIMENTS = {
    # E16/E17: Whisper mit den bisher besten Hyperparametern (aus 02_)
    # um einen fairen Vergleich mit BL4 bei gleichen Decoding-Parametern zu ermöglichen
    "E16_whisper_bs8_len20": {
    "base_model": "whisper_large_v3",
    "beam_size": 8,
    "max_length": 20,
    "comment": "Whisper Large-v3, beam=8, len=20",
    },
    
    "E17_whisper_bs12_len20": {
    "base_model": "whisper_large_v3",
    "beam_size": 12,
    "max_length": 20,
    "comment": "Whisper Large-v3, beam=12, len=20",
    },
}


## 4 – Inference

2 Experimente × 5 Sessions = 10 Läufe.

In [5]:
for sid in SESSION_IDS:
    session_dir = f"data-bin/dev/{sid}"
    print(f"\n########## Starte Experimente für {sid} ##########")

    for exp_name in EXPERIMENTS:
        run_inference_for_experiment(
            exp_name=exp_name,
            base_models=MODELS,
            experiments=EXPERIMENTS,
            session_dir=session_dir,
        )


########## Starte Experimente für session_40 ##########

Starte Inference für Experiment: E16_whisper_bs8_len20
  base_model      = whisper_large_v3
  model_type      = whisper_audio
  checkpoint_path = large-v3
  beam_size       = 8
  max_length      = 20
  output_dir_name = output_E16_whisper_bs8_len20
  session_dir     = data-bin/dev_without_central_videos/dev/session_40
  comment         = Whisper Large-v3, beam=8, len=20
Loading whisper_audio model...
Loading Whisper model 'large-v3' on device cuda


100%|█████████████████████████████████████| 2.88G/2.88G [00:55<00:00, 56.0MiB/s]


whisper_audio model loaded successfully!
Inferring 1 sessions using whisper_audio model
Processing session session_40


Processing speakers:   0%|          | 0/6 [00:00<?, ?it/s]


Processing speakers:  17%|█▋        | 1/6 [01:17<06:28, 77.75s/it]


Processing speakers:  33%|███▎      | 2/6 [03:25<07:07, 106.97s/it]


Processing speaker spk_2 track 1 of 3: 0it [00:00, ?it/s]

Processing speaker spk_2 track 2 of 3: 100%|██████████| 13/13 [01:09<00:00,  5.34s/it]

Processing speakers:  50%|█████     | 3/6 [05:32<05:48, 116.04s/it]


Processing speaker spk_3 track 1 of 2: 100%|██████████| 18/18 [01:06<00:00,  3.68s/it]

Processing speakers:  67%|██████▋   | 4/6 [07:32<03:55, 117.91s/it]


Processing speakers:  83%|████████▎ | 5/6 [09:35<01:59, 119.48s/it]


Processing speakers: 100%|██████████| 6/6 [11:39<00:00, 116.64s/it]



Starte Inference für Experiment: E17_whisper_bs12_len20
  base_model      = whisper_large_v3
  model_type      = whisper_audio
  checkpoint_path = large-v3
  beam_size       = 12
  max_length      = 20
  output_dir_name = output_E17_whisper_bs12_len20
  session_dir     = data-bin/dev_without_central_videos/dev/session_40
  comment         = Whisper Large-v3, beam=12, len=20
Loading whisper_audio model...
Loading Whisper model 'large-v3' on device cuda
whisper_audio model loaded successfully!
Inferring 1 sessions using whisper_audio model
Processing session session_40


Processing speakers:   0%|          | 0/6 [00:00<?, ?it/s]


Processing speakers:  17%|█▋        | 1/6 [01:45<08:47, 105.42s/it]


Processing speakers:  33%|███▎      | 2/6 [04:42<09:51, 147.86s/it]


Processing speaker spk_2 track 1 of 3: 0it [00:00, ?it/s]

Processing speaker spk_2 track 2 of 3: 100%|██████████| 13/13 [01:35<00:00,  7.33s/it]

Processing speakers:  50%|█████     | 3/6 [07:27<07:47, 155.68s/it]


Processing speaker spk_3 track 1 of 2: 100%|██████████| 18/18 [01:29<00:00,  4.97s/it]

Processing speakers:  67%|██████▋   | 4/6 [10:16<05:21, 160.77s/it]


Processing speakers:  83%|████████▎ | 5/6 [12:44<02:36, 156.19s/it]


Processing speakers: 100%|██████████| 6/6 [16:00<00:00, 160.01s/it]



########## Starte Experimente für session_43 ##########

Starte Inference für Experiment: E16_whisper_bs8_len20
  base_model      = whisper_large_v3
  model_type      = whisper_audio
  checkpoint_path = large-v3
  beam_size       = 8
  max_length      = 20
  output_dir_name = output_E16_whisper_bs8_len20
  session_dir     = data-bin/dev_without_central_videos/dev/session_43
  comment         = Whisper Large-v3, beam=8, len=20
Loading whisper_audio model...
Loading Whisper model 'large-v3' on device cuda
whisper_audio model loaded successfully!
Inferring 1 sessions using whisper_audio model
Processing session session_43


Processing speakers:   0%|          | 0/6 [00:00<?, ?it/s]


Processing speaker spk_0 track 1 of 2: 100%|██████████| 27/27 [01:34<00:00,  3.49s/it]

Processing speakers:  17%|█▋        | 1/6 [02:01<10:06, 121.21s/it]


Processing speakers:  33%|███▎      | 2/6 [03:22<06:31, 97.80s/it] 


Processing speakers:  50%|█████     | 3/6 [05:00<04:53, 97.97s/it]


Processing speakers:  67%|██████▋   | 4/6 [07:34<04:00, 120.11s/it]


Processing speaker spk_4 track 1 of 2: 100%|██████████| 16/16 [00:43<00:00,  2.72s/it]

Processing speakers:  83%|████████▎ | 5/6 [09:10<01:51, 111.27s/it]


Processing speakers: 100%|██████████| 6/6 [10:41<00:00, 106.96s/it]



Starte Inference für Experiment: E17_whisper_bs12_len20
  base_model      = whisper_large_v3
  model_type      = whisper_audio
  checkpoint_path = large-v3
  beam_size       = 12
  max_length      = 20
  output_dir_name = output_E17_whisper_bs12_len20
  session_dir     = data-bin/dev_without_central_videos/dev/session_43
  comment         = Whisper Large-v3, beam=12, len=20
Loading whisper_audio model...
Loading Whisper model 'large-v3' on device cuda
whisper_audio model loaded successfully!
Inferring 1 sessions using whisper_audio model
Processing session session_43


Processing speakers:   0%|          | 0/6 [00:00<?, ?it/s]


Processing speaker spk_0 track 1 of 2: 100%|██████████| 27/27 [02:07<00:00,  4.71s/it]

Processing speakers:  17%|█▋        | 1/6 [02:37<13:09, 157.86s/it]


Processing speakers:  33%|███▎      | 2/6 [04:23<08:28, 127.20s/it]


Processing speakers:  50%|█████     | 3/6 [06:29<06:20, 126.80s/it]


Processing speakers:  67%|██████▋   | 4/6 [09:51<05:12, 156.43s/it]


Processing speaker spk_4 track 1 of 2: 100%|██████████| 16/16 [00:55<00:00,  3.50s/it]

Processing speakers:  83%|████████▎ | 5/6 [11:59<02:26, 146.08s/it]


Processing speakers: 100%|██████████| 6/6 [13:56<00:00, 139.35s/it]



########## Starte Experimente für session_49 ##########

Starte Inference für Experiment: E16_whisper_bs8_len20
  base_model      = whisper_large_v3
  model_type      = whisper_audio
  checkpoint_path = large-v3
  beam_size       = 8
  max_length      = 20
  output_dir_name = output_E16_whisper_bs8_len20
  session_dir     = data-bin/dev_without_central_videos/dev/session_49
  comment         = Whisper Large-v3, beam=8, len=20
Loading whisper_audio model...
Loading Whisper model 'large-v3' on device cuda
whisper_audio model loaded successfully!
Inferring 1 sessions using whisper_audio model
Processing session session_49


Processing speakers:   0%|          | 0/6 [00:00<?, ?it/s]


Processing speakers:  17%|█▋        | 1/6 [00:29<02:27, 29.48s/it]


Processing speakers:  33%|███▎      | 2/6 [01:16<02:38, 39.66s/it]


Processing speaker spk_2 track 1 of 8: 100%|██████████| 1/1 [00:00<00:00,  1.10it/s]

Processing speaker spk_2 track 2 of 8: 100%|██████████| 1/1 [00:00<00:00,  1.02it/s]

Processing speaker spk_2 track 3 of 8: 100%|██████████| 1/1 [00:01<00:00,  1.02s/it]

Processing speaker spk_2 track 4 of 8: 100%|██████████| 3/3 [00:22<00:00,  7.49s/it]

Processing speaker spk_2 track 5 of 8: 100%|██████████| 2/2 [00:06<00:00,  3.26s/it]

Processing speaker spk_2 track 6 of 8: 100%|██████████| 8/8 [00:31<00:00,  3.97s/it]

Processing speaker spk_2 track 7 of 8: 100%|██████████| 3/3 [00:08<00:00,  2.84s/it]

Processing speakers:  50%|█████     | 3/6 [02:54<03:19, 66.34s/it]


Processing speakers:  67%|██████▋   | 4/6 [04:11<02:21, 70.64s/it]


Processing speakers:  83%|████████▎ | 5/6 [05:45<01:19, 79.17s/it]


Processing speaker spk_5 track 1 of 2: 100%|██████████| 21/21 [01:08<00:00,  3.24s/it]

Processing speakers: 100%|██████████| 6/6 [07:31<00:00, 75.19s/it]



Starte Inference für Experiment: E17_whisper_bs12_len20
  base_model      = whisper_large_v3
  model_type      = whisper_audio
  checkpoint_path = large-v3
  beam_size       = 12
  max_length      = 20
  output_dir_name = output_E17_whisper_bs12_len20
  session_dir     = data-bin/dev_without_central_videos/dev/session_49
  comment         = Whisper Large-v3, beam=12, len=20
Loading whisper_audio model...
Loading Whisper model 'large-v3' on device cuda
whisper_audio model loaded successfully!
Inferring 1 sessions using whisper_audio model
Processing session session_49


Processing speakers:   0%|          | 0/6 [00:00<?, ?it/s]


Processing speakers:  17%|█▋        | 1/6 [00:36<03:02, 36.59s/it]


Processing speakers:  33%|███▎      | 2/6 [01:39<03:28, 52.16s/it]


Processing speaker spk_2 track 1 of 8: 100%|██████████| 1/1 [00:01<00:00,  1.01s/it]

Processing speaker spk_2 track 2 of 8: 100%|██████████| 1/1 [00:01<00:00,  1.17s/it]

Processing speaker spk_2 track 3 of 8: 100%|██████████| 1/1 [00:01<00:00,  1.23s/it]

Processing speaker spk_2 track 4 of 8: 100%|██████████| 3/3 [00:30<00:00, 10.04s/it]

Processing speaker spk_2 track 5 of 8: 100%|██████████| 2/2 [00:08<00:00,  4.32s/it]

Processing speaker spk_2 track 6 of 8: 100%|██████████| 8/8 [00:44<00:00,  5.56s/it]

Processing speaker spk_2 track 7 of 8: 100%|██████████| 3/3 [00:09<00:00,  3.03s/it]

Processing speakers:  50%|█████     | 3/6 [03:49<04:22, 87.61s/it]


Processing speakers:  67%|██████▋   | 4/6 [05:30<03:05, 92.76s/it]


Processing speakers:  83%|████████▎ | 5/6 [07:34<01:44, 104.16s/it]


Processing speaker spk_5 track 1 of 2: 100%|██████████| 21/21 [01:17<00:00,  3.70s/it]

Processing speakers: 100%|██████████| 6/6 [09:35<00:00, 95.84s/it] 



########## Starte Experimente für session_50 ##########

Starte Inference für Experiment: E16_whisper_bs8_len20
  base_model      = whisper_large_v3
  model_type      = whisper_audio
  checkpoint_path = large-v3
  beam_size       = 8
  max_length      = 20
  output_dir_name = output_E16_whisper_bs8_len20
  session_dir     = data-bin/dev_without_central_videos/dev/session_50
  comment         = Whisper Large-v3, beam=8, len=20
Loading whisper_audio model...
Loading Whisper model 'large-v3' on device cuda
whisper_audio model loaded successfully!
Inferring 1 sessions using whisper_audio model
Processing session session_50


Processing speakers:   0%|          | 0/6 [00:00<?, ?it/s]


Processing speakers:  17%|█▋        | 1/6 [01:08<05:40, 68.17s/it]


Processing speakers:  33%|███▎      | 2/6 [02:35<05:18, 79.56s/it]


Processing speaker spk_2 track 1 of 2: 100%|██████████| 18/18 [00:55<00:00,  3.08s/it]

Processing speakers:  50%|█████     | 3/6 [03:50<03:51, 77.18s/it]


Processing speaker spk_3 track 1 of 3: 100%|██████████| 16/16 [00:40<00:00,  2.56s/it]

Processing speaker spk_3 track 2 of 3: 100%|██████████| 11/11 [00:34<00:00,  3.12s/it]

Processing speakers:  67%|██████▋   | 4/6 [05:29<02:52, 86.09s/it]


Processing speakers:  83%|████████▎ | 5/6 [06:45<01:22, 82.26s/it]


Processing speakers: 100%|██████████| 6/6 [08:31<00:00, 85.27s/it]



Starte Inference für Experiment: E17_whisper_bs12_len20
  base_model      = whisper_large_v3
  model_type      = whisper_audio
  checkpoint_path = large-v3
  beam_size       = 12
  max_length      = 20
  output_dir_name = output_E17_whisper_bs12_len20
  session_dir     = data-bin/dev_without_central_videos/dev/session_50
  comment         = Whisper Large-v3, beam=12, len=20
Loading whisper_audio model...
Loading Whisper model 'large-v3' on device cuda
whisper_audio model loaded successfully!
Inferring 1 sessions using whisper_audio model
Processing session session_50


Processing speakers:   0%|          | 0/6 [00:00<?, ?it/s]


Processing speakers:  17%|█▋        | 1/6 [01:31<07:37, 91.55s/it]


Processing speakers:  33%|███▎      | 2/6 [03:28<07:05, 106.31s/it]


Processing speaker spk_2 track 1 of 2: 100%|██████████| 18/18 [01:13<00:00,  4.08s/it]

Processing speakers:  50%|█████     | 3/6 [05:06<05:08, 102.77s/it]


Processing speaker spk_3 track 1 of 3: 100%|██████████| 16/16 [00:53<00:00,  3.34s/it]

Processing speaker spk_3 track 2 of 3: 100%|██████████| 11/11 [00:47<00:00,  4.30s/it]

Processing speakers:  67%|██████▋   | 4/6 [07:18<03:48, 114.20s/it]


Processing speakers:  83%|████████▎ | 5/6 [08:46<01:44, 104.88s/it]


Processing speakers: 100%|██████████| 6/6 [11:09<00:00, 111.52s/it]



########## Starte Experimente für session_54 ##########

Starte Inference für Experiment: E16_whisper_bs8_len20
  base_model      = whisper_large_v3
  model_type      = whisper_audio
  checkpoint_path = large-v3
  beam_size       = 8
  max_length      = 20
  output_dir_name = output_E16_whisper_bs8_len20
  session_dir     = data-bin/dev_without_central_videos/dev/session_54
  comment         = Whisper Large-v3, beam=8, len=20
Loading whisper_audio model...
Loading Whisper model 'large-v3' on device cuda
whisper_audio model loaded successfully!
Inferring 1 sessions using whisper_audio model
Processing session session_54


Processing speakers:   0%|          | 0/5 [00:00<?, ?it/s]


Processing speaker spk_0 track 1 of 2: 100%|██████████| 26/26 [01:41<00:00,  3.89s/it]

Processing speakers:  20%|██        | 1/5 [02:04<08:18, 124.67s/it]


Processing speakers:  40%|████      | 2/5 [04:15<06:24, 128.26s/it]


Processing speakers:  60%|██████    | 3/5 [06:11<04:05, 122.63s/it]


Processing speakers:  80%|████████  | 4/5 [08:59<02:20, 140.73s/it]


Processing speakers: 100%|██████████| 5/5 [10:48<00:00, 129.79s/it]



Starte Inference für Experiment: E17_whisper_bs12_len20
  base_model      = whisper_large_v3
  model_type      = whisper_audio
  checkpoint_path = large-v3
  beam_size       = 12
  max_length      = 20
  output_dir_name = output_E17_whisper_bs12_len20
  session_dir     = data-bin/dev_without_central_videos/dev/session_54
  comment         = Whisper Large-v3, beam=12, len=20
Loading whisper_audio model...
Loading Whisper model 'large-v3' on device cuda
whisper_audio model loaded successfully!
Inferring 1 sessions using whisper_audio model
Processing session session_54


Processing speakers:   0%|          | 0/5 [00:00<?, ?it/s]


Processing speaker spk_0 track 1 of 2: 100%|██████████| 26/26 [02:01<00:00,  4.65s/it]

Processing speakers:  20%|██        | 1/5 [02:38<10:35, 158.84s/it]


Processing speakers:  40%|████      | 2/5 [05:25<08:09, 163.32s/it]


Processing speakers:  60%|██████    | 3/5 [08:10<05:28, 164.09s/it]


Processing speakers:  80%|████████  | 4/5 [12:06<03:12, 192.46s/it]


Processing speakers: 100%|██████████| 5/5 [14:29<00:00, 173.92s/it]


## 5 – Evaluation & Aggregation

In [6]:
# Ergebnisse auswerten und an gemeinsame CSV anhängen
df_dev = append_eval_results_for_experiments(
    experiments=EXPERIMENTS,
    session_ids=SESSION_IDS,
    target_csv="results_dev_subset_by_session.csv",
)



########## Evaluate für session_40 ##########
Starte Evaluate: /home/josch080/Projektgruppe/mcorec_train/bin/python script/evaluate.py --session_dir data-bin/dev_without_central_videos/dev/session_40 --output_dir_name output_ --label_dir_name labels
Evaluating 1 sessions

=== Evaluating session session_40 ===

--- Evaluating output dir: output_E01_bs4_len15 ---
Conversation clustering F1 score: 1.0
Speaker to WER: {'spk_0': 0.564, 'spk_1': 0.4281, 'spk_2': 0.5576, 'spk_3': 0.4283, 'spk_4': 0.4793, 'spk_5': 0.4189}
Speaker clustering F1 score: {'spk_0': 1.0, 'spk_1': 1.0, 'spk_2': 1.0, 'spk_3': 1.0, 'spk_4': 1.0, 'spk_5': 1.0}
Joint ASR-Clustering Error Rate: {'spk_0': 0.282, 'spk_1': 0.21405, 'spk_2': 0.2788, 'spk_3': 0.21415, 'spk_4': 0.23965, 'spk_5': 0.20945}

--- Evaluating output dir: output_E02_bs8_len15 ---
Conversation clustering F1 score: 1.0
Speaker to WER: {'spk_0': 0.561, 'spk_1': 0.4312, 'spk_2': 0.5506, 'spk_3': 0.4283, 'spk_4': 0.5041, 'spk_5': 0.4189}
Speaker clusterin

## 6 – Vergleich: Whisper vs. BL4

Whisper-Ergebnisse (E16, E17) werden den besten BL4-Konfigurationen (E08, E09) gegenübergestellt.

In [7]:
import pandas as pd

dev_df = pd.read_csv("results_dev_subset_by_session.csv")

# Whisper-Ergebnisse über alle Sessions mitteln
whisper_models = ["E16_whisper_bs8_len20", "E17_whisper_bs12_len20"]
whisper_df = (
    dev_df[dev_df["model"].isin(whisper_models)]
    .groupby("model")[["avg_speaker_wer", "avg_joint_error"]]
    .mean()
    .reset_index()
)

# BL4-Referenz: beste Konfigurationen aus 02_ (beam=8/12, len=20)
best_avsr_models = ["E08_bs8_len20", "E09_bs12_len20"]
avsr_df = (
    dev_df[dev_df["model"].isin(best_avsr_models)]
    .groupby("model")[["avg_speaker_wer", "avg_joint_error"]]
    .mean()
    .reset_index()
)

print("Whisper:")
display(whisper_df)
print("AVSR finetuned:")
display(avsr_df)


Whisper:


model  avg_speaker_wer  avg_joint_error
0   E16_whisper_bs8_len20         1.031613         0.591999
1  E17_whisper_bs12_len20         1.025096         0.588740

AVSR finetuned:


model  avg_speaker_wer  avg_joint_error
0   E08_bs8_len20         0.495798         0.324091
1  E09_bs12_len20         0.495416         0.323900

## 7 – Interpretation

| Modell | WER | Joint Error | rel. Δ WER vs. BL4 |
|--------|-----|-------------|--------------------|
| Whisper Large-v3 (beam=8/12) | ~1.03 | ~0.59 | +~108 % |
| BL4 (beam=12, len=20) | ~0.495 | ~0.324 | – |

Whisper ist mit einer WER von 1.03 mehr als doppelt so fehleranfällig wie BL4.
Auch die Joint Error Rate (0.59 vs. 0.324) liegt deutlich höher.

**Warum ist Whisper so viel schlechter?**

1. **Kein visueller Input:** In der überlappenden Mehrsprecher-Umgebung von MCoRec
   liefern Lip-Crops pro Sprecher entscheidende Kontextinformation, die Whisper fehlt.
2. **Kein In-Domain-Fine-Tuning:** Whisper wurde auf generischen Audiodaten trainiert,
   nicht auf MCoRec-spezifischen Sprachmustern und Vokabular.
3. **Fehlende Sprecher-Segmentierung:** Ohne sprecher-spezifische Eingabe produziert
   Whisper viele Insertions und inhaltlich abweichende Wörter, was WER und JER stark erhöht.

**Schlussfolgerung:** Audio-only ASR ist für die MCoRec-Challenge ungeeignet.
Der audio-visuelle Ansatz von BL4 bleibt die Basis für alle weiteren Experimente.
